### PR TITLE
Fix viewer modal & minor fixes

### LINKED ISSUE #243: Fix report window location
screenshot from 2018-11-17 11-37-33

Example sites:
https://www.polskieradio.pl/7/129/Artykul/2153675
https://www.radiozet.pl/Radio/Programy/Gosc-Radia-ZET/Jacek-Sasin-Nigdy-nie-zapowiadalismy-500-dla-emerytow

### LINKED ISSUE #267: Remove "www" from annotation link title domain

### LINKED ISSUE #277: Implement annotation delete modal with custom Modal

### PR DESCRIPTION
**Pull request by kaglowka**
Resolve #277
Resolve #267 
Resolve #243

### CODE REVIEW

File: src/content-scripts/components/elements/Modal/Modal.tsx [hunk 1]
```diff
@@ -15,7 +15,7 @@ export default class Modal extends React.PureComponent<ModalProps> {
 
     render() {
         return (
-            <div className={classNames(PPScopeClass, styles.modal)} onClick={() => this.props.onCloseModal()}>
```
Comment (glowka) [inline src/content-scripts/components/elements/Modal/Modal.tsx]: :+1:

File: src/content-scripts/components/viewer/DeleteAnnotationModal.tsx [hunk 2]
```diff
@@ -1,17 +1,15 @@
 import React from 'react';
 import { connect } from 'react-redux';
 import { deleteResource } from 'redux-json-api';
-import { Button, Modal } from 'semantic-ui-react';
```
Comment (glowka) [inline src/content-scripts/components/viewer/DeleteAnnotationModal.tsx]: Good to be getting rid of this dependency step by step  :)
