### PR TITLE
Add crucial information in HTTP headers: site URL and CSRF token + context menu fix

### LINKED ISSUE #176: Modify PP GET annotation requests to correspond the backend privacy improvements
Solution architecture in backend issue: https://github.com/PrzypisPowszechny/pp/issues/39

### Frontend details

We need to  create `readPostEndopint` basing on `readEndpoint` which will do the same as the latter, but using `POST` method. This means copying the body of it `readPoint` from https://github.com/redux-json-api/redux-json-api/blob/9e4210af054e3ccdc61c312480de09ba844760fd/src/jsonapi.js#L85 and adding just few lines.

Beside that we could create the issue in https://github.com/redux-json-api/redux-json-api/ and ask for adding options to `readEndpoint` which would be passed to the request, but that library is very specialized and we cannot be certain it will be accepted.

### LINKED ISSUE #218: Add sending X-CSRFToken header with every request
Using this hook: https://github.com/axios/axios#interceptors

This issue should be completed before merging: https://github.com/PrzypisPowszechny/pp/pull/70

### PR DESCRIPTION
**Pull request by kaglowka**
Resolves #176 
Resolves #218 

CSRF token is available via chrome extension background page `chrome.cookies` API, since traditional `document.cookie` won't return the cookies set by HTTP requests since the API domain and background-page/content script domain differ.

The already complicated webpack configuration got temporarily slightly more complicated and simplifying it should be a priority.

After merging, merge https://github.com/PrzypisPowszechny/pp/pull/70

### CODE REVIEW

File: src/content-scripts/init-API.ts [hunk 1]
```diff
@@ -0,0 +1,46 @@
+import store from './store/store';
+import axios from 'axios';
+import { setAxiosConfig } from 'redux-json-api';
+
+function getExtensionCookie(name: string) {
```
Comment (glowka) [inline src/content-scripts/init-API.ts]: Nice! I am gonna use it with ppGA soon

Comment (kaglowka) [reply src/content-scripts/init-API.ts]: I didn't export it just yet, but I thought of it as a util-to-be ;)
